site:
  title: Drogue IoT
  start_page: drogue-book::index.adoc
  keys:
    google_analytics: 'G-Z4BRXRBJJ1'

content:
  sources:
    - url: ./
      branches: main
      start_path: docs
    - url: https://github.com/drogue-iot/drogue-cloud.git
      branches: [main, v*, release-*]
      start_path: docs
    - url: https://github.com/drogue-iot/drogue-ajour.git
      branches: [main]
      start_path: docs
    - url: https://github.com/drogue-iot/drogue-device.git
      branches: main
      start_path: docs
    - url: https://github.com/embassy-rs/embassy.git
      branches: master
      start_path: docs
    - url: https://github.com/drogue-iot/drogue-workshops.git
      branches: main

antora:
  extensions:
    - require: '@antora/lunr-extension'
    - require: ./extensions/openapi.js
      queries:
        - component: drogue-cloud
          module: api
        - component: drogue-ajour
          module: api

ui:
  bundle:
    url: https://github.com/drogue-iot/drogue-antora-ui/releases/download/v0.2.0/ui-bundle.zip
    snapshot: false

  supplemental_files:
    - path: ui.yml
      contents: |
        static_files: [ .nojekyll, CNAME ]
    - path: .nojekyll
    - path: CNAME
      contents: |
        book.drogue.io

output:
  clean: true

runtime:
  fetch: true
  log:
    failure_level: error

